<a href="https://colab.research.google.com/github/Meghana3683/ML/blob/main/embeddings_using_supervisedlearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just amazing',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement',
        'terribel food']

sentiment = np.array([1,1,1,1,1,1,0,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[18, 7]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[23, 3], [18, 7], [3, 27], [16, 18], [16, 23, 10], [22, 3, 5], [8, 3], [13, 3, 10], [5, 16], [5, 29], [12, 4], [15, 3]]


In [5]:
#padding 
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[23  3  0  0]
 [18  7  0  0]
 [ 3 27  0  0]
 [16 18  0  0]
 [16 23 10  0]
 [22  3  5  0]
 [ 8  3  0  0]
 [13  3 10  0]
 [ 5 16  0  0]
 [ 5 29  0  0]
 [12  4  0  0]
 [15  3  0  0]]


In [7]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))  #sigmoid activation function is used .

In [9]:
X = padded_reviews  # x is labeled as padded_reviews
y = sentiment       # y is labeled as sentiment 

In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) # loss function used is binary_crossentropy (0 or 1)
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_1 (Flatten)         (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [11]:
model.fit(X, y, epochs=50, verbose=0)

In [12]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 263ms/step - loss: 0.6430 - accuracy: 1.0000


1.0

In [13]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [14]:
weights[13]

array([ 0.00255671, -0.03898178, -0.01670118, -0.0136462 ,  0.06650921],
      dtype=float32)

In [15]:
weights[5]

array([ 0.06774563, -0.01265641,  0.0203312 , -0.037588  ,  0.06317762],
      dtype=float32)

In [16]:
weights[17]

array([ 0.04381699, -0.0147896 ,  0.03461665,  0.04849618, -0.00457642],
      dtype=float32)